import { GetStaticProps } from "next";
import Head from "next/head";

import { Header } from "../components";
import Country from "../models/country";

// prefetch this info on the server before painting the page
export const getStaticProps: GetStaticProps = async () => {
  const countriesResponse = await fetch(
    "https://disease.sh/v3/covid-19/countries"
  );
  const countries: Promise<Country[]> = await countriesResponse.json();

  return { props: { countries } };
};

interface HomeProps extends Country {
  countries: Country[];
}

export default function Home({ countries }: HomeProps) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header countries={countries} />
      </main>
    </div>
  );
}
