import { GetStaticProps } from "next";
import Head from "next/head";
import { useEffect } from "react";
import styled from "styled-components";

import { AppLeft, AppRight } from "../components";
import { useStore } from "../hooks";
import { Country, CountryInfo } from "../models";

// prefetch this info on the server before painting the page
export const getStaticProps: GetStaticProps = async () => {
  const countriesResponse = await fetch(
    "https://disease.sh/v3/covid-19/countries"
  );
  const countries = await countriesResponse.json();

  const allCountryInfoResponse = await fetch(
    "https://disease.sh/v3/covid-19/all"
  );
  const allCountryInfo = await allCountryInfoResponse.json();

  return {
    props: { allCountryInfo, countries }
  };
};

interface HomeProps extends Country {
  allCountryInfo: CountryInfo;
  countries: Country[];
}

export default function Home({ allCountryInfo, countries }: HomeProps) {
  const setCountries = useStore(state => state.setCountries);
  const setAllCountryInfo = useStore(state => state.setAllCountryInfo);

  useEffect(() => {
    setCountries(countries);
    setAllCountryInfo(allCountryInfo);
  }, []);

  return (
    <div>
      <Head>
        <title>Covid-19 Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <AppLeft />

        <AppRight />
      </Main>
    </div>
  );
}

const Main = styled.main`
  display: flex;
  justify-content: space-evenly;
  padding-top: 20px;

  @media (max-width: 990px) {
    flex-direction: column;
  }
`;
